apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: dockered-jenkins:v3
          imagePullPolicy: IfNotPresent
          volumeMounts:
                - name: jenkins-home
                  mountPath: /var/lib/jenkins-home
          ports:
            - containerPort: 8080
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc