apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: devops
spec:
  project: default
  source:
    repoURL: https://github.com/alexandr-cassa/ac-k8s.git
    targetRevision: HEAD
    path: nexus
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
        prune: true
        selfHeal: true